### ISSUE TITLE
Maximum sleep time due to LDL_MAC_ticksUntilNextEvent() values

### ISSUE THREAD

**Issue by frbehrens** [cjhdev/lora_device_lib#19]
Hello,
 I updated successfully to the latest version 0.4.5 (https://github.com/cjhdev/lora_device_lib/commit/597630c030b035fc6f82aaf9916cefd466268693).

I see a different behaviour, compared to previous versions. The function LDL_MAC_ticksUntilNextEvent() returns always values less than 60 seconds, due to a armed LDL_TIMER_BAND timer. I use the value to calculate possible power down times for my application and that value is rather short.

Is it really necessary to have a timer for band events? The processing function is in any case called from LDL_MAC_process and at first glance I see no problems if more ticks elapse before the next call. I would like to get UINT32_MAX from LDL_MAC_ticksUntilNextEvent() when the last receive window is closed and no (MAC) messages are queued.

Kind regards,
    Frank

**Comment by cjhdev** [comment]
Hello

Previous versions also set the band timer to 60s. It's a legacy thing. I kept it because the low power MCUs I use wake up regularly when hardware timers overflow and so it made no difference.

The interval could be increased. I would choose a maximum of INT32_MAX ticks as a way to ensure the time tracking in processBands() never overflows. I notice processBands() ignores differences larger than INT32_MAX but that can be changed.

LDL_TIMER_BAND exists because it seemed easier to use a single purpose timer rather than overload one of the others and then have to work out which part of the code was responsible for clearing it. 

I think it is useful to have an event for when a ldl_mac.band counts down to zero. Perhaps LDL_MAC_ticksUntilNextEvent() should be refactored to check ldl_mac.band as well as inputs and timers.

**Comment by cjhdev** [comment]
I've increased LDL_TIMER_BAND interval in master to a large number that won't break time tracking

**Comment by frbehrens** [comment]
> I've increased LDL_TIMER_BAND interval in master to a large number that won't break time tracking

Thanks!

**Comment by frbehrens** [comment]
Meanwhile I found a working solution for my use case, so I reopen the issue to document it. The comitted changes for LDL_TIMER_BAND interval were not sufficient.

Summary of my requirements: 
I'm able to call LDL_MAC_process() regulary, with a maximum interval of several minutes, but want to deep sleep when no transmission or receive event is pending. So I want to distinguish between "important" events (retry of transmission, when channel is not available; wait for reiceive window; ..) and "unimportant" events (band events). In the latter case the LDL_MAC_ticksUntilNextEvent() wait time should not inhibit the sleep.

My solution:
I call LDL_MAC_process() in a loop only, when the mac.state is not LDL_STATE_IDLE. To compensate the missed band events after a deep sleep I ensure that LDL_MAC_process() is called before any other LDL function call.
As a result the process runs in the LDL_MAC_process() loop only after a transmit request - until the transmit was successful and the receive windows elapsed. Afterwards the device goes to deep sleep for several minutes.

**Comment by cjhdev** [comment]
Thanks for sharing your workaround.

I don't think there is a quick fix to avoid spurious wakeups with the current implementation, the whole thing needs to be reworked.

**Comment by cjhdev** [comment]
I've solved this problem in my current working branch (sx1262). I expect to merge this month.

**Comment by frbehrens** [comment]
I'm still running my mentioned solution with the new LDL version (https://github.com/cjhdev/lora_device_lib/commit/450ae80c2ca5b2651df0536d1c6157c6dfeb9807). It works well. I have also implemented a check for a maximum sleep time, so even between longer retransmission attempts (channel not available, OTAA pending) I can go into deep sleep. I see only the requirements, that after deep sleep the timer is roughly adjusted and LDL_MAC_process() is called again.

I see that LDL_MAC_priority() may also help in many situations, but did not touch my existing solution.

I close the issue, because solutions exists for the described requirement.
