### ISSUE TITLE
possible deprecated #define LDL_LITTLE_ENDIAN

### ISSUE THREAD

**Issue by szemzoa** [cjhdev/lora_device_lib#24]
Hi,

I'd ported this nice little library to my custom cortex m0+ microcontroller, but with the LDL_LITTLE_ENDIAN define the OTAA authentication fails, with "joinAccept MIC failed" error.

After removing the define it successfully join and packets are ok, so this option is possibly deprecated or buggy.

**Comment by cjhdev** [comment]
I've located the problem, fix is in master.

I was passing pointer to pointer instead of pointer in a few of the LDL_Stream_get* functions. No warnings were produced since the required type is void pointer. Whoops.
