### ISSUE TITLE
LPTIM 16 bit ticker

### ISSUE THREAD

**Issue by marsam94** [cjhdev/lora_device_lib#34]
Hello, I'm using using an STM32L4 and thus I'm using LPTimer. The timer has a 16 bit resolution but the system ticks used in LDL assume the timer has a 32 bit resolution. 
I read in another issue that you also use LPTIM so how do you solve this problem ?

regards

**Comment by cjhdev** [comment]
Use the overflow interrupt to increment a software counter.
