### ISSUE TITLE
OTAA join-accept not being received 

### ISSUE THREAD

**Issue by gonzabrusco** [cjhdev/lora_device_lib#50]
Hello. First of all I would like to thank you for the amazing library you wrote. I'm using it instead of loramac-node because your library is so much smaller. Also is not Arduino dependant like lmic (mcci port). 

Anyway, I ported your code to a STM32 with a RFM95. The frequency plan I'm using is AU915 and for the development I use TTN. I was able to make the library transmit perfectly, but for some reason I'm not receiving correctly the OTAA response. This is the debug output from your library (plus some added by me).

```
tx begin
ticks=8630550 freq=917600000 power=0  bw=125000 sf=10 size=23
DIO0 Interrupt 8667667
offtime=100
tx complete
ticks=8668127
rx1 slot
ticks=9167831 timeout=8 lag=0 freq=925700000 bw=500000 sf=10
DIO1 Interrupt 9169402
rx2 slot
ticks=9266908 timeout=8 lag=1 freq=923300000 bw=500000 sf=12
DIO1 Interrupt 9273411
LDL_MAC_DEV_NONCE_UPDATED: 4
waiting to retry OTAA
```

I can see on the TTN console that the gateway is sending the downlink with the network join accept. But nevertheless, LDL is not receiving it. Not sure what to try. Could you give me a hint on what to test to find the problem? 

![image](https://github.com/cjhdev/lora_device_lib/assets/2846883/6d5022c1-d477-4124-aacd-4060404afbad)

**Comment by cjhdev** [comment]
Sorry, I'm not sure what it could be, I've not looked at the code in a long time.

**Comment by gonzabrusco** [comment]
Don't worry. Your code is fine. I was having a timing issue. I increased the "A" parameter, and now I'm receiving the OTAA join accept fine.

Thanks!
